name: jack_social_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.14.0
  intl: ^0.18.1
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true