// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJmPtsAPo9KROns6q2uhwzDCX6_xHY4U',
    appId: '1:881122469323:android:4da78c774088a99fc6024e',
    messagingSenderId: '881122469323',
    projectId: 'chat-app-91a9d',
    databaseURL: 'https://chat-app-91a9d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-91a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLW7guOzj3tDZUWzH6BwqatExC6WOlMo',
    appId: '1:881122469323:ios:c925511e1053170ac6024e',
    messagingSenderId: '881122469323',
    projectId: 'chat-app-91a9d',
    databaseURL: 'https://chat-app-91a9d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-91a9d.appspot.com',
    androidClientId: '881122469323-4vgifp6vhnm4hhpsq917j7jpcuo34pfm.apps.googleusercontent.com',
    iosClientId: '881122469323-g735csnjebgl9bq4per5l2id8se3127j.apps.googleusercontent.com',
    iosBundleId: 'com.jacksoftware.jackSocialApp',
  );
}
